namespace: development

microservice1:
  name: microservice1
  image:
    repository: us-central1-docker.pkg.dev/heroic-gamma-465105-c8/microservicequiz/microservice1
    tag: 5
    pullPolicy: IfNotPresent
  containerPort: 80

microservice2:
  name: microservice2
  image:
    repository: us-central1-docker.pkg.dev/heroic-gamma-465105-c8/microservicequiz/microservice2
    tag: 5
    pullPolicy: IfNotPresent
  containerPort: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: ""  # optional for DNS, empty for IP access
