namespace: development

ingress:
  enabled: true
  className: nginx
  host: microservices.example.com  # Or your external IP (for GCP without domain)

microservice1:
  name: service-one
  port: 80

microservice2:
  name: service-two
  port: 80
