apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-app
  namespace: argocd
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/mokadi-suryaprasad/microservices-Helm-charts.git
    targetRevision: HEAD
    path: .
    helm:
      releaseName: microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
