{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: microservices
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: /microservice1
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.microservice1.name }}
                port:
                  number: 80
          - path: /microservice2
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.microservice2.name }}
                port:
                  number: 80
{{- end }}
