apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice2.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.microservice2.name }}
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
