apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice2
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice2
  template:
    metadata:
      labels:
        app: microservice2
    spec:
      containers:
        - name: microservice2
          image: "{{ .Values.microservice2.image.repository }}@{{ .Values.microservice2.image.tag }}"
          imagePullPolicy: {{ .Values.microservice2.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.microservice2.containerPort }}
