apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
        - name: microservice1
          image: "{{ .Values.microservice1.image.repository }}@{{ .Values.microservice1.image.tag }}"
          imagePullPolicy: {{ .Values.microservice1.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.microservice1.containerPort }}
