apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice1.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.microservice1.containerPort }}
  selector:
    app: {{ .Values.microservice1.name }}
