apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice1.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.microservice1.name }}
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
