apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice2.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.microservice2.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.microservice2.containerPort }}
  type: ClusterIP
