apiVersion: v1
kind: Service
metadata:
  name: microservice2
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: microservice2
  ports:
    - port: 80
      targetPort: {{ .Values.microservice2.containerPort }}
