apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice2.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.microservice2.containerPort }}
  selector:
    app: {{ .Values.microservice2.name }}
