apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice1.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.microservice1.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.microservice1.containerPort }}
