{{- range $svc := list .Values.microservice1 .Values.microservice2 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: {{ $svc.name }}
  ports:
    - port: 80
      targetPort: {{ $svc.containerPort }}
---
{{- end }}
