apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.microservice2.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.microservice2.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.microservice2.name }}
    spec:
      containers:
        - name: {{ .Values.microservice2.name }}
          image: "{{ .Values.microservice2.image }}"
          imagePullPolicy: {{ .Values.microservice2.pullPolicy }}
          ports:
            - containerPort: {{ .Values.microservice2.containerPort }}
