apiVersion: v1
kind: Service
metadata:
  name: microservice1
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: microservice1
  ports:
    - port: 80
      targetPort: {{ .Values.microservice1.containerPort }}
